name: genz_store
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


#---------------------- PACKAGES----------------------#
dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.3.1

  # Utility packages
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.6.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  connectivity_plus: ^5.0.1
  flutter_launcher_icons: ^0.14.4

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.1
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11


#---------------------- APP LOGO----------------------#
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/genz-store-splash-screen-logo-square.png"

#---------------------- ./ PACKAGES END ----------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  #---------------------- LOCAL ASSETS ----------------------#
  assets:
    - assets/logos/
    - assets/user/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/category/
    - assets/images/banners/
    - assets/images/products/
    - assets/animations/on_boarding_animations/
    - assets/animations/lottie_global/

  #---------------------- LOCAL FONTS ----------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/coolvetica_regular.ttf
          weight: 400
        - asset: assets/fonts/coolvetica_regular_italic.ttf
          weight: 400
          style: italic
